// Concept tags and wrong-answer diagnoses for content/environmental-science.js.
window.AP_DIAG = window.AP_DIAG || {};
window.AP_DIAG["environmental-science"] = {
  "0.0": [2, { 0: "2,000 kcal reaches PRIMARY consumers. Secondary consumers are one more level up.", 2: "20 kcal is tertiary consumers, one level too far.", 3: "18,000 kcal is the energy LOST in the first transfer." }],
  "0.1": [5, { 0: "Denitrification returns nitrogen to the atmosphere as N₂.", 2: "Transpiration is part of the water cycle.", 3: "Respiration releases CO₂; it doesn't fix nitrogen." }],
  "0.2": [5, { 0: "Phosphorus has no significant atmospheric reservoir.", 2: "Plants need phosphorus for DNA, ATP and membranes.", 3: "Photosynthesis doesn't produce phosphorus." }],
  "0.3": [1, { 0: "In commensalism only one species benefits; here both do.", 2: "In parasitism one is harmed; neither is harmed here.", 3: "They aren't competing for a resource." }],
  "1.0": [2, { 0: "Small and far means low immigration and high extinction, so the fewest species.", 2: "Small islands have higher extinction rates.", 3: "Far islands receive fewer immigrants." }],
  "1.1": [1, { 0: "Provisioning services are products like food or timber, not the process of pollination.", 2: "Cultural services are recreation and spiritual value.", 3: "Pollination is worth billions of dollars to agriculture." }],
  "1.2": [6, { 0: "Primary succession starts without soil.", 2: "Island biogeography is about species richness on islands.", 3: "Eutrophication is nutrient overload in water." }],
  "1.3": [0, { 0: "Reproduction speed isn't what genetic diversity provides.", 2: "Genetic diversity doesn't reduce predators.", 3: "Genetic diversity is about variety, not population size." }],
  "2.0": [4, { 0: "70 ÷ 3.5 = 20, not 10.", 2: "35 years would be a 2% growth rate.", 3: "70 years would be a 1% growth rate." }],
  "2.1": [1, { 0: "Houseflies have many offspring quickly (r-selected).", 1: "Mice reproduce early and often (r-selected).", 3: "Dandelions spread many seeds (r-selected)." }],
  "2.2": [3, { 0: "Exponential growth can't continue past carrying capacity.", 2: "Reproductive strategy doesn't change because of overshoot.", 3: "Reproduction slows, but a die-off is the typical result." }],
  "2.3": [2, { 0: "Type I is high survival until old age.", 1: "Type II is a constant death rate.", 3: "Logistic describes population growth, not survivorship." }],
  "3.0": [0, { 0: "Divergent boundaries pull apart.", 1: "Convergent boundaries collide.", 3: "Subduction happens at convergent boundaries." }],
  "3.1": [1, { 0: "Clay has tiny particles and holds water.", 1: "Silt drains moderately, not fastest.", 3: "Loam is a balanced mix and drains moderately." }],
  "3.2": [3, { 0: "Tropospheric ozone is a harmful pollutant, not the protective layer.", 2: "The mesosphere is above the ozone layer.", 3: "The thermosphere is far above the ozone layer." }],
  "3.3": [6, { 0: "El Niño WEAKENS upwelling.", 2: "Peruvian fisheries are strongly affected.", 3: "The effect is temporary, not a permanent shift." }],
  "4.0": [0, { 1: "Biomagnification is about toxins moving up food chains.", 2: "Succession is community change over time.", 3: "The 10% rule describes energy transfer." }],
  "4.1": [3, { 0: "Flood irrigation wastes a lot of water through evaporation and runoff.", 1: "Furrow irrigation loses water in channels.", 3: "Spray irrigation loses water to evaporation and wind." }],
  "4.2": [3, { 0: "Desertification is land degrading into desert, not salt buildup.", 2: "Eutrophication happens in water.", 3: "Subsidence is sinking land from groundwater loss." }],
  "4.3": [4, { 0: "Heavy spraying is the opposite of IPM and speeds up resistance.", 2: "Monocultures make pest problems worse.", 3: "Fertilizer doesn't control pests." }],
  "5.0": [1, { 0: "Natural gas emits about half the CO₂ of coal per unit of energy.", 2: "Nuclear emits no CO₂ during operation.", 3: "Wind produces no emissions when running." }],
  "5.1": [2, { 0: "Nuclear plants don't emit CO₂ while operating.", 2: "Nuclear doesn't depend on sunlight.", 3: "Nuclear has very high energy output." }],
  "5.2": [4, { 0: "Dams don't burn fuel to generate power.", 2: "Dams generate power day and night.", 3: "Uranium is for nuclear power." }],
  "5.3": [5, { 0: "Convert to a percent: 0.35 × 100 = 35%.", 2: "65% is the energy LOST, not the efficiency.", 3: "Efficiency can't exceed 100%." }],
  "6.0": [0, { 0: "CO is emitted directly, so it's primary.", 1: "SO₂ is emitted directly from burning coal.", 3: "Particulates are emitted directly." }],
  "6.1": [3, { 0: "CO₂ contributes slightly to acidity but isn't the main cause of acid rain.", 2: "CFCs deplete stratospheric ozone.", 3: "Radon is an indoor air pollutant." }],
  "6.2": [2, { 0: "The greenhouse effect traps heat globally, not pollution in a valley.", 2: "Acid deposition is about acids falling to Earth.", 3: "El Niño is an ocean–atmosphere pattern." }],
  "6.3": [5, { 0: "Catalytic converters clean vehicle exhaust.", 2: "Photovoltaic cells make electricity from sunlight.", 3: "Baghouses capture particles, not SO₂ gas." }],
  "7.0": [0, { 0: "A point source has one identifiable outlet, like a pipe.", 2: "Thermal pollution is heated water.", 3: "Bioaccumulation is toxin buildup in organisms." }],
  "7.1": [1, { 0: "Nutrients aren't directly toxic at these levels; oxygen loss kills the fish.", 2: "Warmer water holds less oxygen, but decomposition is the main cause.", 3: "Eutrophication doesn't increase salinity." }],
  "7.2": [2, { 0: "Producers have the LOWEST concentration.", 1: "Zooplankton are low in the food chain.", 2: "Small fish have less mercury than the predators that eat them." }],
  "7.3": [5, { 0: "Primary treatment physically removes solids.", 2: "Tertiary treatment removes nutrients and chemicals.", 3: "Disinfection kills pathogens; it doesn't break down organic matter." }],
  "8.0": [0, { 0: "CO₂ was addressed by the Kyoto Protocol and the Paris Agreement.", 2: "Acid rain was addressed by the Clean Air Act.", 3: "Overfishing is managed by fishery agreements." }],
  "8.1": [3, { 0: "Warming causes bleaching, but acidification specifically affects shell building.", 2: "Acidification doesn't raise oxygen levels.", 3: "Acidification isn't about added nutrients." }],
  "8.2": [5, { 0: "Invasive species are serious, but habitat loss is the leading cause.", 2: "Pollution matters, but habitat loss is bigger.", 3: "Overhunting affects some species, but habitat loss affects the most." }],
  "8.3": [2, { 0: "A negative feedback counteracts change; this one amplifies it.", 2: "Permafrost is releasing carbon here, not storing it.", 3: "A thermal inversion is an atmospheric layering event." }]
};
