// Concept tags and wrong-answer diagnoses for content/european-history.js.
window.AP_DIAG = window.AP_DIAG || {};
window.AP_DIAG["european-history"] = {
  "0.0": [0, { 0: "Machiavelli did the opposite: he judged rulers by results, not Christian virtue.", 2: "The Prince advises a single ruler. It isn't a call for democracy.", 3: "Attacks on Church doctrine came later, from Luther and other reformers." }],
  "0.1": [2, { 0: "The Columbian Exchange moved crops and diseases, not books.", 2: "The price revolution was inflation from American silver.", 3: "The Inquisition suppressed ideas; it didn't spread them." }],
  "0.2": [5, { 0: "New diseases devastated the Americas, not Europe.", 2: "The slave trade GREW with plantation agriculture.", 3: "American silver caused inflation, not deflation." }],
  "0.3": [3, { 0: "New monarchs curbed the nobles' power.", 2: "Elected parliaments with real power came much later.", 3: "They raised taxes to pay for armies and bureaucracies." }],
  "1.0": [0, { 0: "Backing Luther WEAKENED the emperor, which is why princes liked it.", 2: "Princes had no reason to oppose printing, and printing spread Luther's ideas.", 3: "The Jesuits were a Catholic order fighting Protestantism." }],
  "1.1": [3, { 0: "Faith alone was Luther's teaching. Trent affirmed faith AND works.", 2: "Clerical celibacy was kept.", 3: "Calvinism was recognized by the Peace of Westphalia, not Trent." }],
  "1.2": [4, { 0: "The edict did the opposite. Louis XIV later revoked it.", 2: "France stayed Catholic; Huguenots were tolerated as a minority.", 3: "The Thirty Years' War ended in 1648 with Westphalia." }],
  "1.3": [4, { 0: "Westphalia weakened papal and imperial influence.", 2: "Germany stayed divided until 1871.", 3: "It recognized Calvinism alongside Lutheranism and Catholicism." }],
  "2.0": [0, { 0: "The Estates-General didn't meet at all under Louis XIV.", 2: "Versailles was a palace, not a fortress.", 3: "Louis XIV persecuted Protestants and revoked the Edict of Nantes." }],
  "2.1": [1, { 0: "It did the opposite: it LIMITED the monarch.", 2: "The Church of England dates to Henry VIII in 1534.", 3: "The monarchy survived; William and Mary ruled under the law." }],
  "2.2": [3, { 0: "Peter strengthened serfdom. Russia's serfs were freed in 1861.", 2: "Peter was an absolute ruler.", 3: "He greatly expanded the army." }],
  "2.3": [2, { 0: "That describes Louis XIV's France, not the Dutch.", 2: "The Dutch relied on their navy and commerce.", 3: "Overseas trade was the core of Dutch wealth." }],
  "3.0": [2, { 0: "Hobbes defended strong, even absolute, government.", 2: "Louis XIV claimed divine right, the opposite of consent.", 3: "Calvin was a religious reformer, not a political philosopher of rights." }],
  "3.1": [2, { 0: "Montesquieu opposed concentrated power.", 2: "Abolishing property was a later socialist idea.", 3: "Mercantilism was criticized by Adam Smith, not advocated by Montesquieu." }],
  "3.2": [4, { 0: "She actually strengthened serfdom after Pugachev's Rebellion.", 2: "She kept absolute power; there was no real parliament.", 3: "She embraced Western ideas and corresponded with Voltaire." }],
  "3.3": [0, { 0: "He used the telescope to make his discoveries.", 2: "Galileo was a Catholic and didn't deny God.", 3: "His trial was about astronomy, not Protestantism." }],
  "4.0": [0, { 0: "Napoleon's coup came in 1799, ten years later.", 2: "The Congress of Vienna met after Napoleon's defeat.", 3: "The Terror happened in 1793–1794, after the Revolution began." }],
  "4.1": [4, { 0: "It confirmed the END of noble privileges.", 2: "It gave men legal equality but limited women's rights.", 3: "It protected private property." }],
  "4.2": [5, { 0: "The Congress aimed to suppress revolution.", 2: "It kept Germany and Italy divided.", 3: "No European parliament was created." }],
  "4.3": [2, { 0: "The Terror came during war and crisis, not peace.", 2: "Napoleon's defeat came 20 years later.", 3: "The Congress of Vienna came long after the Terror ended." }],
  "5.0": [0, { 0: "Britain wasn't Europe's most populous country; resources and institutions mattered more.", 2: "Britain's agricultural revolution helped industrialization.", 3: "Britain depended on trade and colonial markets." }],
  "5.1": [5, { 0: "Marx focused on economic classes, not individuals.", 2: "Marx called religion \"the opium of the people\"; it wasn't his driver of history.", 3: "Marx saw class loyalty as more basic than national loyalty." }],
  "5.2": [4, { 0: "Output was rising; the acts addressed working conditions.", 2: "The French Revolution wasn't the target of these laws.", 3: "The Zollverein was a German customs union." }],
  "5.3": [3, { 1: "The middle class grew during industrialization.", 2: "Child labor continued long after 1820; the Factory Acts only limited it.", 3: "Factories replaced the putting-out system." }],
  "6.0": [3, { 0: "Bismarck opposed liberals and used war.", 2: "He fought three wars to unify Germany.", 3: "Bismarck fought socialism." }],
  "6.1": [1, { 0: "Divisions among revolutionaries were a key reason they failed.", 2: "Most rulers regained power.", 3: "Cities were centers of revolutionary support." }],
  "6.2": [5, { 1: "Deism is an Enlightenment religious view, not a justification for empire.", 2: "Divine right justified monarchy, not late-1800s imperialism.", 3: "Sola fide is a Protestant belief about salvation." }],
  "6.3": [2, { 0: "That was Garibaldi.", 2: "The Manifesto was Marx and Engels.", 3: "Cavour was a Piedmontese statesman, not a Paris revolutionary." }],
  "7.0": [0, { 0: "The League of Nations was created after WWI.", 2: "The Great Depression began in 1929.", 3: "Versailles ended WWI." }],
  "7.1": [2, { 0: "Russians were exhausted by the war; the Provisional Government's decision to continue fighting cost it support.", 2: "The Bolsheviks executed the tsar and his family.", 3: "The Bolsheviks were communists." }],
  "7.2": [3, { 1: "The Congress of Vienna was a century earlier.", 2: "The Marshall Plan helped Germany after WWII.", 3: "Unification in 1871 wasn't resented; it was celebrated." }],
  "7.3": [5, { 0: "Normandy (1944) was an invasion, the opposite of appeasement.", 2: "The Nazi-Soviet Pact was between Germany and the USSR.", 3: "Collectivization was Stalin's farm policy." }],
  "8.0": [0, { 0: "Punishing Germany was Versailles after WWI.", 2: "The Warsaw Pact was the Soviet alliance.", 3: "The Plan funded European recovery, not independence movements." }],
  "8.1": [4, { 0: "Gorbachev wanted to save communism by reforming it.", 2: "His reforms moved AWAY from Stalinism.", 3: "The USSR never sought to join NATO." }],
  "8.2": [2, { 0: "The Cold War began from U.S.-Soviet rivalry.", 2: "Germany was divided by the Allies after WWII.", 3: "Welfare states grew in the same period." }],
  "8.3": [3, { 1: "Colonies remained valuable; the powers were weakened.", 2: "The League of Nations no longer existed after 1946.", 3: "The Congress of Vienna was in 1815." }],
};
