// Concept tags and wrong-answer diagnoses for content/sat.js.
window.AP_DIAG = window.AP_DIAG || {};
window.AP_DIAG["sat"] = {
  "0.0": [0, { 0: "The text never says coyotes are dangerous. That's outside knowledge, not the passage.", 2: "Nothing in the text is about population size.", 3: "GPS collars are how they studied it, not the point of the text." }],
  "0.1": [2, { 0: "Being the largest group isn't the same as being most of the teens. The claim is about a majority.", 2: "\"At least monthly\" isn't what the claim says. It says at least weekly.", 3: "True, but it doesn't directly test the claim. You need daily + weekly compared with half of 200." }],
  "0.2": [1, { 0: "Hunting time says nothing about urchins or kelp.", 2: "Kelp growth rate doesn't involve otters at all.", 3: "Where urchins live doesn't show the otter → urchin → kelp link." }],
  "0.3": [3, { 0: "The text says literacy was already rising before the press, so the press can't be the only cause.", 2: "Nothing suggests literacy fell.", 3: "The text never discusses when the press was invented." }],
  "1.0": [0, { 0: "Verbose means wordy, but readers finished it in minutes.", 2: "Ambiguous means unclear, but readers understood every point.", 3: "Tedious means boring and long, which contradicts finishing in minutes." }],
  "1.1": [1, { 0: "The text never says Kevlar is used in tires; that was only her goal.", 2: "The sentence explains why the solution looked useless, not that technicians were careless.", 3: "The comparison with steel comes in the LAST sentence." }],
  "1.2": [2, { 0: "Text 2's evidence goes against Text 1, not with it.", 2: "Text 2 is about employment effects, not whether workers deserve raises.", 3: "Text 2 cites a study, so it doesn't claim economists ignore wages." }],
  "1.3": [3, { 0: "\"Bold\" is praise, so \"entirely reckless\" is too extreme.", 2: "Calling it a bold step implies it's important.", 3: "\"Taken in the dark\" means the results aren't known yet." }],
  "2.0": [0, { 0: "Accurate, but it's about location, not size.", 2: "Too vague: it leaves out both size details.", 3: "This is about coral reefs in general, not this reef's size." }],
  "2.1": [2, { 0: "\"Similarly\" signals a similarity, but the second sentence contrasts with the first.", 1: "\"Therefore\" signals a result, but high cost doesn't follow from panels being cheaper.", 3: "The second sentence isn't an example of panels getting cheaper." }],
  "2.2": [3, { 0: "\"However\" signals a contrast, but the second sentence adds detail to the first.", 2: "\"In contrast\" needs two different things being compared.", 3: "\"Meanwhile\" signals something happening at the same time, not a detail." }],
  "2.3": [1, { 0: "This states a similarity, but the goal is a contrast.", 2: "Only one setting is named, so there's nothing to contrast.", 3: "This is about when they were written, not their settings, and it shows a similarity." }],
  "3.0": [0, { 0: "A comma alone can't join two complete sentences (comma splice).", 2: "No punctuation creates a run-on sentence.", 3: "The extra comma after \"and\" is incorrect." }],
  "3.1": [2, { 0: "\"Maps\" isn't the subject. The subject is \"collection,\" which is singular.", 2: "\"Were\" is plural and past tense, but \"now\" signals present tense.", 3: "\"Have been\" is plural; the subject \"collection\" is singular." }],
  "3.2": [3, { 0: "\"It's\" means \"it is,\" which doesn't fit.", 2: "\"Company\" is singular, so \"their\" doesn't agree.", 3: "\"Its'\" isn't a word." }],
  "3.3": [1, { 0: "This puts a comma between the subject and its verb.", 1: "A single comma before the name isn't paired, and the name is essential here.", 3: "A semicolon needs complete sentences on both sides." }],
  "4.0": [0, { 0: "Check the signs: subtract 2x AND add 7 to both sides.", 2: "You may have subtracted 7 instead of adding it.", 3: "That's 5 − 7 + 4 rather than 5 + 7." }],
  "4.1": [4, { 0: "This charges $40 per month and $25 once, reversed.", 2: "The $40 fee is paid once, not every month.", 3: "The fee is added to the monthly total, not subtracted." }],
  "4.2": [2, { 0: "With k = 3, the slopes differ, so there's exactly one solution.", 2: "k = 12 doesn't make the coefficients proportional.", 3: "The sign is wrong: 2/4 = 3/k needs k = 6." }],
  "4.3": [1, { 0: "5 is the y-intercept, not the x-intercept.", 1: "The sign is wrong: solving 0 = −2x + 5 gives a positive x.", 3: "You multiplied instead of dividing by the slope." }],
  "5.0": [0, { 0: "The sum of the roots is −b/a = −(−5)/1 = +5.", 1: "6 is the PRODUCT of the roots (c/a), not the sum.", 3: "1 is the difference of the roots." }],
  "5.1": [1, { 0: "0.05 is the rate; the growth factor is 1 + 0.05 = 1.05.", 2: "Adding 0.05t is linear growth, not a 5% increase each year.", 3: "1.5 means 50% growth each year." }],
  "5.2": [2, { 0: "(x + 3)² includes a middle term: 2·3·x = 6x.", 2: "The middle term is +6x, not −6x.", 3: "(x + 3)² ≠ x² + 9. Don't forget the middle term." }],
  "5.3": [4, { 0: "x = 2 is extraneous: √9 = 3 but 2 − 5 = −3.", 2: "Check both answers in the original equation. Only 9 works.", 3: "x = 9 does work: √16 = 4 = 9 − 5." }],
  "6.0": [1, { 0: "20 is the dollar change, not the percent.", 2: "That divides by the new price (60) instead of the original (80).", 3: "75% is what's left of the original price, not the decrease." }],
  "6.1": [0, { 0: "That uses 50 mph. The rate is 150 ÷ 2.5 = 60 mph.", 2: "Recompute the unit rate: 150 ÷ 2.5 = 60, so 60 × 4 = 240.", 3: "That multiplies 150 by 2.5 instead of dividing." }],
  "6.2": [2, { 0: "The median is 5 both before and after removing 30.", 2: "The outlier strongly affects the mean, which drops from 10 to 5.", 3: "Removing an outlier changes the mean a lot." }],
  "6.3": [4, { 0: "A sample estimate has a margin of error. It's not exact for the whole school.", 2: "The sample came from one school, so it can't generalize to all U.S. students.", 3: "Random samples are valid without surveying everyone." }],
  "7.0": [2, { 1: "Legs don't add directly. Use a² + b² = c².", 2: "12 isn't correct: √(36 + 64) = √100 = 10.", 3: "48 is ½ × 6 × 8 × 2 or the product of the legs, not the hypotenuse." }],
  "7.1": [2, { 0: "4/5 is cos A. cos(90° − A) equals sin A.", 2: "5/3 is the reciprocal (csc A).", 3: "3/4 is tan A." }],
  "7.2": [3, { 0: "You need to complete the square first; 12 isn't r².", 1: "12 is on the right side before completing the square, and it's not the radius.", 3: "25 is r², so r = 5." }],
  "7.3": [1, { 0: "Equal angles are alternate interior angles; same-side interior angles add to 180°.", 2: "25° would make them complementary, but these are supplementary.", 3: "130° doubles 65°; the pair adds to 180°." }]
};
