// "AP Trap" for every concept in content/environmental-science.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["environmental-science"] = {
  "0.0": "Biomes are set by temperature AND precipitation. Name both when explaining a biome's location.",
  "0.1": "Mutualism benefits both; commensalism benefits one and doesn't affect the other. Read carefully.",
  "0.2": "Energy is LOST as heat at each level; it isn't recycled. Only about 10% moves up.",
  "0.3": "Removing a keystone species changes the whole food web, not just its prey.",
  "0.4": "Photosynthesis removes CO₂; respiration and combustion add it. Fossil fuels move carbon from LONG-TERM storage.",
  "0.5": "Phosphorus has no significant gas phase; nitrogen does. That's why phosphorus is often limiting.",
  "0.6": "Most freshwater is in ice and groundwater, not lakes and rivers.",
  "1.0": "Species richness counts species; evenness measures balance. High richness with low evenness is still vulnerable.",
  "1.1": "Ecosystem services have ECONOMIC value. Questions often ask you to connect them to money.",
  "1.2": "Larger and closer islands have more species. Apply the same idea to habitat fragments.",
  "1.3": "Species with narrow tolerance ranges are most at risk from environmental change.",
  "1.4": "Some ecosystems NEED disturbance, like fire-adapted forests.",
  "1.5": "Human-caused changes can happen faster than populations can adapt.",
  "1.6": "Primary succession starts with no soil; secondary succession starts with soil.",
  "2.0": "Specialists are more vulnerable to extinction than generalists.",
  "2.1": "r-selected species are often INVASIVE; K-selected species are often endangered.",
  "2.2": "Type I = most survive to old age; Type III = most die young.",
  "2.3": "Overshooting carrying capacity leads to a die-off, not a gentle leveling off.",
  "2.4": "Use the rule of 70 for doubling time, and convert per-1,000 rates into percents.",
  "2.5": "In the demographic transition, DEATH rates fall first, then birth rates.",
  "3.0": "Transform boundaries cause earthquakes but not volcanoes; convergent boundaries cause both.",
  "3.1": "Sand drains fastest; clay holds the most water; loam is best for crops.",
  "3.2": "Plowing up and down a slope increases erosion. Contour plowing follows the land's shape.",
  "3.3": "Stratospheric ozone is protective; ground-level ozone is a pollutant.",
  "3.4": "Deserts form around 30° latitude, where dry air sinks, not at the equator.",
  "3.5": "Everything upstream in a watershed affects water quality downstream.",
  "3.6": "El Niño WEAKENS upwelling off South America, hurting fisheries.",
  "4.0": "Solutions to the tragedy of the commons include regulation, quotas and permits. Name a specific one.",
  "4.1": "Clear-cutting increases erosion AND stream temperatures. Selective cutting reduces both.",
  "4.2": "Monocultures reduce biodiversity and make crops more vulnerable to pests.",
  "4.3": "Drip irrigation is the most efficient; flood irrigation is the least.",
  "4.4": "Heavy pesticide use breeds resistant pests. IPM reduces chemical use.",
  "4.5": "Impervious surfaces in cities increase runoff and flooding.",
  "4.6": "Aquaculture reduces pressure on wild fish but can cause pollution and disease.",
  "5.0": "Biomass is renewable only if it's replanted, and burning it still emits CO₂.",
  "5.1": "Coal emits the most CO₂ per unit of energy; natural gas emits the least of the fossil fuels.",
  "5.2": "Nuclear power emits no CO₂ during operation. Its main drawback is radioactive waste.",
  "5.3": "Solar and wind are intermittent and need storage or backup.",
  "5.4": "Dams trap sediment and block fish migration, even though they don't burn fuel.",
  "5.5": "Efficiency = useful output ÷ total input. It can never exceed 100%.",
  "6.0": "Ground-level ozone and acid rain are SECONDARY pollutants: they form in the air.",
  "6.1": "Smog peaks on hot, sunny days, because sunlight drives the reactions.",
  "6.2": "Inversions TRAP pollution; they don't create it.",
  "6.3": "Acid rain comes from SO₂ and NOx, not CO₂.",
  "6.4": "Radon is the leading indoor cause of lung cancer after smoking.",
  "6.5": "Scrubbers remove SO₂; catalytic converters clean vehicle exhaust. Match the technology to the pollutant.",
  "7.0": "Farm and urban runoff are NONPOINT sources, which are harder to regulate.",
  "7.1": "Fish die from LOW OXYGEN caused by decomposing algae, not from the nutrients themselves.",
  "7.2": "Biomagnification concentrates toxins in TOP predators.",
  "7.3": "A lower LD50 means a MORE toxic substance.",
  "7.4": "The priority order is reduce, then reuse, then recycle.",
  "7.5": "Secondary treatment is biological; tertiary removes nutrients.",
  "7.6": "Climate change can expand the range of vector-borne diseases like malaria.",
  "8.0": "Ozone depletion (CFCs, UV) and global warming (greenhouse gases, heat) are DIFFERENT problems.",
  "8.1": "The natural greenhouse effect is necessary for life; the ENHANCED effect causes warming.",
  "8.2": "Melting permafrost is a POSITIVE feedback: it amplifies warming.",
  "8.3": "Acidification comes from CO₂ dissolving in seawater, not from acid rain.",
  "8.4": "Invasive species are often r-selected generalists with no natural predators in their new habitat.",
  "8.5": "Habitat loss is the leading cause of biodiversity loss. Remember HIPPCO.",
  "8.6": "Mitigation reduces emissions; adaptation prepares for effects. Questions may ask for one specifically."
};
