// "AP Trap" for every concept in content/european-history.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["european-history"] = {
  "0.0": "Renaissance humanism wasn't anti-religious. Most humanists were Christians who also valued classical learning.",
  "0.1": "Northern Renaissance art is more religious and detailed; don't describe it with only Italian examples.",
  "0.2": "The printing press didn't cause the Reformation by itself, but it made Luther's ideas spread fast.",
  "0.3": "New monarchs weren't yet absolute. They were centralizing, but nobles and the Church still had power.",
  "0.4": "Exploration had economic, religious and political motives. Name more than one when asked about causes.",
  "0.5": "The price revolution was inflation caused partly by American silver. It hurt people on fixed incomes.",
  "1.0": "Luther didn't intend to start a new church at first; he wanted to reform the Catholic Church.",
  "1.1": "Calvinists weren't tolerant. Geneva enforced strict moral rules.",
  "1.2": "Henry VIII's break with Rome was political; the church kept many Catholic practices at first.",
  "1.3": "The Catholic Reformation wasn't only a reaction. Reform movements began inside the Church before Luther.",
  "1.4": "The Peace of Augsburg did NOT include Calvinism. That came with Westphalia in 1648.",
  "1.5": "The Reformation didn't give women equality. It emphasized their roles as wives and mothers.",
  "2.0": "Absolutism still needed cooperation; Louis XIV relied on intendants and nobles, not just force.",
  "2.1": "The Glorious Revolution was mostly bloodless; the Civil War was not. Don't mix them up.",
  "2.2": "The Dutch Republic wasn't a democracy; wealthy merchants dominated it.",
  "2.3": "Serfdom declined in Western Europe but became STRONGER in Eastern Europe in this period.",
  "2.4": "Balance-of-power wars were often global, fought in colonies as well as in Europe.",
  "2.5": "Enclosure increased food production but pushed many rural poor off the land.",
  "3.0": "The Scientific Revolution mostly involved a small educated elite, not ordinary people.",
  "3.1": "Bacon is induction and empiricism; Descartes is deduction and rationalism. Don't swap them.",
  "3.2": "Hobbes used the social contract to support strong government; Locke used it to limit government.",
  "3.3": "Most Enlightenment thinkers were deists or reformers, not atheists.",
  "3.4": "Enlightened absolutists reformed to make the state stronger, not to share power.",
  "3.5": "Most Europeans were still rural peasants in the 1700s despite urban growth.",
  "4.0": "The Revolution didn't begin with the poor alone; the Third Estate included wealthy bourgeoisie.",
  "4.1": "The early Revolution aimed at a constitutional monarchy, not a republic.",
  "4.2": "The Terror was a response to war and counterrevolution, not only ideology.",
  "4.3": "Women's activism was real, but the Revolution denied them political rights.",
  "4.4": "Napoleon both preserved and betrayed revolutionary ideals; strong essays show both sides.",
  "4.5": "The Congress of Vienna didn't erase liberal ideas; it only suppressed them for a time.",
  "5.0": "Britain's advantages were a combination of factors, not just coal.",
  "5.1": "The steam engine powered railways and ships, not just factories.",
  "5.2": "Continental industrialization relied more on government support than Britain's did.",
  "5.3": "The middle class also grew with industrialization; it wasn't only a working-class story.",
  "5.4": "Most reforms came gradually through legislation, not revolution.",
  "5.5": "Utopian socialists like Owen wanted cooperation; Marx called for class revolution.",
  "6.0": "Nineteenth-century liberals often opposed universal suffrage; they wanted votes for property owners.",
  "6.1": "The 1848 revolutions failed in the short term, but ideas like ending serfdom in Austria lasted.",
  "6.2": "Italy was unified by both diplomacy (Cavour) and popular campaigns (Garibaldi).",
  "6.3": "German unification was led by conservative Prussia, not liberals.",
  "6.4": "Alexander II freed the serfs, but they still owed payments and had little land.",
  "6.5": "Imperialism had economic AND ideological motives, like Social Darwinism.",
  "6.6": "Darwin's work was scientific; Social Darwinism was a misuse of it.",
  "7.0": "The assassination was the spark; alliances and militarism were the long-term causes.",
  "7.1": "Total war affected civilians, including women's work and government control of economies.",
  "7.2": "The February Revolution removed the tsar; the October Revolution brought the Bolsheviks.",
  "7.3": "The Treaty of Versailles alone didn't cause WWII; the Great Depression also mattered.",
  "7.4": "Hitler came to power legally as chancellor in 1933, then destroyed democracy.",
  "7.5": "Appeasement was popular at the time because people feared another world war.",
  "7.6": "The Holocaust was state-organized genocide, not just wartime violence.",
  "8.0": "The Cold War involved economic competition and aid, not only military rivalry.",
  "8.1": "Khrushchev's reforms didn't mean freedom; the USSR still crushed revolts.",
  "8.2": "European integration started with coal and steel, not a political union.",
  "8.3": "Decolonization was often violent, as in Algeria, not always peaceful.",
  "8.4": "Gorbachev tried to reform communism, not end it.",
  "8.5": "The EU has faced both expansion and challenges like Brexit and populism.",
  "8.6": "Postwar social change included feminism, secularization and immigration, not just politics.",
};
