// "AP Trap" for every concept in content/macroeconomics.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["macroeconomics"] = {
  "0.0": "Opportunity cost is only the NEXT-BEST alternative, not the sum of everything you gave up.",
  "0.1": "Unemployment moves the economy INSIDE the PPC; it doesn't shift the curve. Only changes in resources or technology shift it.",
  "0.2": "Comparative advantage uses OPPORTUNITY COST, not who can make more. A country can have an absolute advantage in both goods but a comparative advantage in only one.",
  "0.3": "A change in the good's own price moves along the curve. Only non-price factors shift demand or supply.",
  "0.4": "In the circular flow, households SELL factors and BUY products. Firms do the reverse.",
  "0.5": "Macro questions are about aggregates (total output, overall prices). A single market is micro.",
  "0.6": "When both curves shift, one variable is always indeterminate. Say so instead of guessing.",
  "1.0": "Intermediate goods, used goods, stocks and transfer payments are NOT in GDP. Only final goods and services produced this year count.",
  "1.1": "Nominal GDP can rise with no increase in output. Use real GDP for growth.",
  "1.2": "Discouraged workers aren't in the labor force, so they don't count as unemployed. The official rate can understate joblessness.",
  "1.3": "Real interest rate ≈ nominal rate − inflation. Unexpected inflation lowers the real rate borrowers pay.",
  "1.4": "Unexpected inflation HELPS borrowers and HURTS lenders and people on fixed incomes.",
  "1.5": "Full employment doesn't mean 0% unemployment. It means no cyclical unemployment.",
  "1.6": "A nominal raise smaller than inflation is a real pay CUT.",
  "2.0": "Changes in the price level move along AD. Only changes in C, I, G or Xn shift it.",
  "2.1": "Changes in input prices (wages, oil) shift SRAS, not AD.",
  "2.2": "LRAS is VERTICAL at full employment. The price level doesn't change long-run output.",
  "2.3": "Self-correction works through WAGES shifting SRAS, and it's slow. That's why policy may be used.",
  "2.4": "The tax multiplier (−MPC/MPS) is smaller than the spending multiplier (1/MPS). Don't mix them up.",
  "2.5": "Buying and selling bonds is MONETARY policy. Fiscal policy is only government spending and taxes.",
  "2.6": "A negative supply shock raises prices AND unemployment at the same time (stagflation).",
  "3.0": "Bond prices and interest rates move in OPPOSITE directions.",
  "3.1": "Credit cards aren't money. They're loans.",
  "3.2": "Only EXCESS reserves can be loaned. Multiply excess reserves, not the whole deposit, by the money multiplier.",
  "3.3": "The money market determines the NOMINAL interest rate; loanable funds determines the REAL rate. Use the right graph.",
  "3.4": "Buying bonds is expansionary (adds reserves); selling bonds is contractionary.",
  "3.5": "Government deficits increase DEMAND for loanable funds, raising the real rate and crowding out private investment.",
  "3.6": "Write the whole chain: tool → money supply → interest rate → investment → AD → output and prices. Skipped steps lose points.",
  "4.0": "Expansionary fiscal policy raises interest rates. Expansionary monetary policy can offset that crowding out.",
  "4.1": "AD shifts move you ALONG the SRPC; SRAS shifts SHIFT the SRPC.",
  "4.2": "The LRPC is vertical at the natural rate of unemployment. There's no long-run trade-off.",
  "4.3": "In the long run, money growth changes only the PRICE LEVEL, not real output.",
  "4.4": "Deficit is a yearly flow; debt is the accumulated stock. Don't use them interchangeably.",
  "4.5": "Growth shifts LRAS and the PPC outward. Short-run AD stimulus doesn't create long-run growth.",
  "4.6": "Supply-side policies aim to shift AS right, lowering prices while raising output. Don't draw them as AD shifts.",
  "5.0": "A current account deficit is always matched by a financial account surplus.",
  "5.1": "A stronger (appreciating) currency REDUCES net exports.",
  "5.2": "In a two-currency market, more demand for one currency means more supply of the other.",
  "5.3": "Higher domestic interest rates attract foreign capital and APPRECIATE the currency.",
  "5.4": "Expansionary monetary policy depreciates the currency and boosts net exports; expansionary fiscal policy does the opposite through higher rates.",
  "5.5": "Tariffs protect specific producers but raise prices for consumers and create deadweight loss."
};
