// "SAT Trap" for every concept in content/sat.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["sat"] = {
  "0.0": "Wrong answers are often a true DETAIL from the passage. The main idea must cover the whole text.",
  "0.1": "The evidence must support the EXACT claim. A related fact that sounds convincing isn't enough.",
  "0.2": "Many choices state true data. Only one is both true AND about the claim in the question.",
  "0.3": "If the passage hedges (\"may,\" \"some evidence\"), the right completion hedges too. Absolute answers are usually wrong.",
  "0.4": "A choice that's true in real life can still be wrong if the passage doesn't say it.",
  "1.0": "Don't pick the fanciest word. Pick the one the sentence's clues demand, especially contrast words like \"yet.\"",
  "1.1": "Purpose questions ask what a sentence DOES (introduces, contrasts, illustrates), not what it says.",
  "1.2": "Answer from Text 2's evidence, aimed at Text 1's specific claim. Choices that mention only one text are traps.",
  "1.3": "Extreme tone words (furious, reckless, ecstatic) are rarely right. Most SAT tones are moderate or mixed.",
  "1.4": "One wrong word makes a whole choice wrong. Check every part, especially the second half.",
  "2.0": "Every choice may be accurate. Only one does what the GOAL asks. Read the goal before the notes.",
  "2.1": "\"Contrast\" requires two things and a difference; \"similarity\" requires a shared feature. Match the goal's verb.",
  "2.2": "Decide the relationship (contrast, cause, example, addition) BEFORE reading the choices, so a smooth-sounding wrong word doesn't fool you.",
  "2.3": "\"For example\" gives one case; \"specifically\" adds precise detail; \"in contrast\" compares two things. They're not interchangeable.",
  "3.0": "A comma alone can't join two complete sentences. Use a period, a semicolon, or a comma plus FANBOYS.",
  "3.1": "Never put a single comma between a subject and its verb. Extra information needs a PAIR of commas.",
  "3.2": "Cross out the prepositional phrase (\"of rare maps\") to find the real subject before choosing the verb.",
  "3.3": "\"It's\" always means \"it is.\" Companies, teams and countries are \"it,\" so they take \"its.\"",
  "3.4": "An opening modifier must describe the subject right after the comma, or it dangles.",
  "4.0": "Distributing a negative changes EVERY sign inside the parentheses.",
  "4.1": "In context questions, the slope is the \"per\" quantity and the intercept is the starting amount. The SAT often asks what one of them means.",
  "4.2": "No solution means the same slope AND a different intercept. The same slope and the same intercept means infinitely many solutions.",
  "4.3": "Dividing or multiplying an inequality by a negative number flips the sign.",
  "4.4": "Check units: a fee in dollars can't be multiplied by months unless it's charged every month.",
  "5.0": "The sum of the roots is −b/a, not b/a. The sign trips up many students.",
  "5.1": "A 5% increase means multiplying by 1.05, not 0.05. A 20% decrease means multiplying by 0.80.",
  "5.2": "(a + b)² is NOT a² + b². The middle term 2ab is always there.",
  "5.3": "f(x − 3) shifts the graph RIGHT 3, not left. The shift goes opposite to the sign.",
  "5.4": "Squaring both sides can create fake solutions. Always substitute your answers back into the original equation.",
  "6.0": "Find the unit rate first, then scale. Setting up the proportion upside down is the common error.",
  "6.1": "Percent change divides by the ORIGINAL value. +20% then −20% is not a net change of zero.",
  "6.2": "Outliers move the mean, not the median. Expect questions on removing an outlier.",
  "6.3": "The slope of a line of best fit is a PREDICTED change. Also, correlation doesn't prove causation.",
  "6.4": "A sample only generalizes to the population it was randomly drawn from, and only within the margin of error.",
  "7.0": "Doubling the lengths quadruples the area and multiplies the volume by 8.",
  "7.1": "Same-side interior angles add to 180°. Alternate interior and corresponding angles are equal.",
  "7.2": "sin x° = cos(90° − x°). Complementary-angle trig questions show up often.",
  "7.3": "Complete the square before reading the radius. The right side of the finished equation is r², not r."
};
