// "AP Trap" for every concept in content/statistics.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["statistics"] = {
  "0.0": "Zip codes and jersey numbers are numbers, but they're categorical. Ask whether averaging them makes sense.",
  "0.1": "Bar graphs have gaps and are for categories. Histograms have touching bars and are for quantitative data.",
  "0.2": "Always describe shape, center, spread and outliers IN CONTEXT. \"Skewed right\" alone loses points.",
  "0.3": "The mean and standard deviation are not resistant. With skew or outliers, report the median and IQR.",
  "0.4": "A z-score only gives normal-table percentiles if the distribution is approximately normal.",
  "0.5": "A large sample doesn't fix bias. Name the bias AND say which direction it pushes the estimate.",
  "0.6": "Random SAMPLING lets you generalize to a population. Random ASSIGNMENT lets you conclude cause. They're different.",
  "1.0": "Mutually exclusive and independent are not the same. Mutually exclusive events with positive probability are always dependent.",
  "1.1": "P(A | B) is not P(B | A). Read which event is given.",
  "1.2": "Describe the simulation fully: what a digit or trial represents, how many trials, and what you record.",
  "1.3": "The expected value is a long-run average. It doesn't have to be a value X can actually take.",
  "1.4": "Check BINS: binary outcomes, independent trials, fixed number of trials, same probability each time.",
  "1.5": "The sampling distribution is the distribution of a statistic over many samples, not the data in one sample.",
  "1.6": "The CLT is about the shape of the sampling distribution of x̄, not the shape of the population or the sample.",
  "2.0": "The interval is about the population parameter p, never about p̂. You already know p̂ exactly.",
  "2.1": "95% confidence is about the method's long-run capture rate, not a 95% chance this particular interval is right.",
  "2.2": "Hypotheses use parameters (p), never statistics (p̂). And never say \"accept H₀\".",
  "2.3": "Power is the probability of correctly rejecting a false H₀. Raising α raises power but also raises Type I error risk.",
  "2.4": "For two-proportion tests, use the pooled p̂ in the standard error. For intervals, don't pool.",
  "2.5": "Chi-square uses COUNTS, not percentages. Check that all expected counts are at least 5.",
  "2.6": "A conclusion needs three parts: compare p to α, state the decision, and say it in context about the alternative.",
  "3.0": "Use t, not z, whenever you estimate σ with s. Degrees of freedom for one sample are n − 1.",
  "3.1": "With small samples, check the sample's graph for strong skew or outliers. Don't just say \"n ≥ 30\" if it isn't.",
  "3.2": "A small p-value means the data are unlikely IF H₀ is true. It is not the probability that H₀ is true.",
  "3.3": "Paired data become one sample of differences. Don't run a two-sample test on them.",
  "3.4": "Two-sample t needs independent groups and uses both standard errors. Don't pool the variances.",
  "3.5": "Decide by data type first: categorical means proportions or chi-square; quantitative means t procedures.",
  "4.0": "Describe direction, form, strength and unusual features, always in context of the two variables.",
  "4.1": "r only measures LINEAR association. A strong curve can have r near 0.",
  "4.2": "Interpret the slope as a PREDICTED change in y for each 1-unit increase in x.",
  "4.3": "Residual = actual − predicted. A positive residual means the line underestimated.",
  "4.4": "r² is the percent of variation in y explained by the linear model with x, not the percent of points on the line.",
  "4.5": "A high-leverage point has an extreme x. It's only influential if removing it changes the line a lot.",
  "4.6": "Predicting far outside the x-values in the data is extrapolation and unreliable. And association isn't causation.",
};
